<<<<<<< Updated upstream
web:
  build: .
  command: ["python3","app.py"]
  ports:
    - "5000:5000"
=======
version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
>>>>>>> Stashed changes
